# Activación obligatoria del ecosistema moderno AndroidX
android.useAndroidX=true

# Permite la compatibilidad con librerías heredadas si fuera necesario
android.enableJetifier=true

# Configuración de estilo de código para Kotlin
kotlin.code.style=official
# Aumentar la memoria del demonio de Gradle para evitar el OutOfMemory
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Activación obligatoria del ecosistema moderno AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Configuración de estilo de código para Kotlin
kotlin.code.style=official